import type { SiteContent } from "./types";

export const en: SiteContent = {
  meta: {
    title: "Lend | A clearer, documented rental experience",
    description:
      "Lend is a Saudi rental platform that brings structure to rentals between customers and rental businesses: a clear offer, a documented contract, recorded handover, an organized rental history, and a structured path when something goes wrong.",
    ogAlt: "Lend — Rent with confidence. Document your right.",
    siteName: "Lend",
    keywords: ["Lend", "rental", "rental contract", "Saudi Arabia", "documented rental", "rental businesses"],
  },
  brand: {
    name: "Lend",
    tagline1: "Rent with confidence.",
    tagline2: "Document your right.",
    taglineFull: "Rent with confidence. Document your right.",
  },
  nav: {
    home: "Home",
    how: "How Lend works",
    customers: "For customers",
    business: "For businesses",
    faq: "FAQ",
    switchLabel: "Change language",
    switchTo: "العربية",
    cta: "Register your business interest",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    skip: "Skip to content",
  },
  hero: {
    eyebrow: "A Saudi rental platform",
    supporting:
      "Lend gives every rental a clear structure: an offer you can read before you agree, a contract both sides can return to, a recorded handover, and one organized history of every rental — with a clear path if a dispute arises.",
    primaryCta: "Explore Lend",
    secondaryCta: "For business owners",
    points: ["A documented contract for every rental", "Item condition recorded at handover", "A structured path when disputes arise"],
    screenLabel: "The rental offer and contract screen in the Lend app",
  },
  why: {
    eyebrow: "01 — Why Lend",
    title: "Undocumented rentals cost both sides",
    intro:
      "Most rental problems don't start at the dispute. They start on day one: missing details, scattered paperwork, and two different memories of what was agreed.",
    beforeTitle: "What happens today",
    afterTitle: "How Lend structures it",
    pains: [
      { title: "Unclear rental details", body: "Duration, price and terms agreed verbally or across scattered messages." },
      { title: "Scattered documentation", body: "Photos on a phone, paper receipts, and chats nobody can find later." },
      { title: "Unknown condition at handover", body: "No one can show what state the item was in when it changed hands." },
      { title: "Weak transaction records", body: "No single record of every rental and where it stands." },
      { title: "Disputes without organized evidence", body: "When things go wrong, each side relies on its own account." },
    ],
    gains: [
      { title: "Clear rental details", body: "Item, price, duration and branch in one offer before anyone agrees." },
      { title: "A contractual record", body: "A rental contract that keeps the agreed terms, available to both sides at any time." },
      { title: "Documented handover and receipt", body: "The item's condition is recorded at pickup and at return." },
      { title: "An organized rental history", body: "Every rental in one place, with its current status." },
      { title: "A structured dispute journey", body: "A documented case with a description and evidence, instead of an open argument." },
    ],
  },
  how: {
    eyebrow: "02 — How Lend works",
    title: "One rental journey, four clear stages",
    intro:
      "Every rental on Lend moves through the same stages, and both sides can see exactly where it stands at any moment.",
    stagesTitle: "Stages of a rental",
    stages: ["Offer & contract issued", "Customer review", "Rental starts", "Return & contract closed"],
    customerTitle: "The customer journey",
    customerSub: "From receiving the offer to closing the rental",
    customer: [
      { title: "Receive the rental offer", body: "The business sends the offer to your Lend account." },
      { title: "Review the details and contract", body: "Item, price, duration and contract terms, before any commitment." },
      { title: "Approve in the app", body: "Your approval is recorded on the contract itself." },
      { title: "Document the receipt", body: "The item's condition is recorded when you collect it from the branch." },
      { title: "Manage your rental", body: "Status, return date and contract in one place." },
      { title: "Return and close", body: "The contract closes once the return is confirmed." },
    ],
    merchantTitle: "The business journey",
    merchantSub: "From confirming the customer to closing the contract",
    merchant: [
      { title: "Confirm the customer's account", body: "Using the mobile number registered on Lend." },
      { title: "Prepare the rental details", body: "Item description, original value, rental price and duration." },
      { title: "Record the contractual data", body: "Customer and item details exactly as they will appear in the contract." },
      { title: "Issue the offer and contract", body: "Sent to the customer to review and approve." },
      { title: "Follow the rental lifecycle", body: "From the start of the rental to the return date." },
      { title: "Manage returns and issues", body: "Confirm receipt, or open a documented damage or non-return case." },
    ],
  },
  customers: {
    eyebrow: "03 — For customers",
    title: "Know everything before you agree",
    intro: "Lend gives you the full picture before you commit, and keeps a record of what happens after.",
    benefits: [
      { icon: "eye", title: "See the rental details before approving", body: "Item, price, duration and branch are clear in the offer." },
      { icon: "document", title: "A clear contract and clear data", body: "Contract terms in plain language, available to you at any time." },
      { icon: "camera", title: "Condition recorded at receipt", body: "The item's condition is documented at pickup, so there is no argument later." },
      { icon: "history", title: "An organized record of your rentals", body: "Active, upcoming and completed, in one list." },
      { icon: "route", title: "A clear path if there is a dispute", body: "If a case is opened, you know what was documented and what is expected of you." },
    ],
  },
  business: {
    eyebrow: "04 — For rental businesses",
    title: "Operational infrastructure for your rental business",
    intro:
      "Lend is not a marketplace for listing products. It is the layer that structures every rental in your store, from issuing the offer to closing the contract.",
    items: [
      { icon: "route", title: "A standardized rental journey", body: "The same steps for every customer and every branch." },
      { icon: "document", title: "Organized contracts", body: "A contract for every rental, stored and linked to the customer and the item." },
      { icon: "phone", title: "Customer account confirmation", body: "Offers are issued to an account confirmed via the mobile number registered on Lend." },
      { icon: "camera", title: "Evidence and documentation", body: "Item condition at handover and return, plus evidence attached to cases." },
      { icon: "layers", title: "Centralized rental tracking", body: "One dashboard for every rental: active, awaiting review, and overdue." },
      { icon: "shield", title: "Structured dispute handling", body: "Damage or non-return cases with a description, evidence and claim amount, on a documented track." },
    ],
    cta: "Register your business interest",
  },
  product: {
    eyebrow: "05 — Product experience",
    title: "What the journey looks like inside Lend",
    intro: "Moments from the customer and business experience in the Lend app, in the product's own visual language.",
    labels: {
      offer: "Rental offer",
      contract: "Contract review",
      receipt: "Receipt evidence",
      status: "Rental status",
      dispute: "Case timeline",
    },
  },
  trust: {
    eyebrow: "06 — Trust & privacy",
    title: "Your data stays within your rental",
    intro: "Here is what Lend actually does with your data. Nothing more.",
    items: [
      {
        icon: "lock",
        title: "Private account access",
        body: "Access to your account is confirmed with a code sent to your registered mobile number. This confirms control of your Lend account; it is not government identity verification.",
      },
      {
        icon: "eye",
        title: "Controlled document access",
        body: "The contract and rental data are visible only to the two parties of that rental.",
      },
      {
        icon: "document",
        title: "Structured contractual records",
        body: "Contract data, including the national ID the business records, is stored as contractual data for that specific rental and reviewed by the customer before approval.",
      },
      {
        icon: "shield",
        title: "Careful handling of sensitive data",
        body: "Interfaces show the minimum data needed, and your data is not used for purposes outside your rental.",
      },
      {
        icon: "history",
        title: "Your transaction history",
        body: "Your rental history is kept for you, with the status and contract of each rental.",
      },
    ],
    note: "Lend structures and documents the rental. It does not issue rulings, does not guarantee legal outcomes, and does not claim certifications it has not obtained.",
  },
  faq: {
    eyebrow: "07 — FAQ",
    title: "Questions customers and businesses ask",
    intro: "Short answers that describe how Lend works today.",
    items: [
      {
        q: "What is Lend?",
        a: "Lend is a Saudi rental platform that structures rentals between customers and rental businesses: a clear offer, a documented contract, a recorded handover, an organized history of every rental, and a clear path when a dispute arises.",
      },
      {
        q: "Is Lend a rental marketplace?",
        a: "No. Lend does not list products and does not rent anything itself. The customer deals directly with the business; Lend structures and documents the rental.",
      },
      {
        q: "Who creates the rental contract?",
        a: "The business prepares the rental details and contractual data, then issues the offer and contract. The customer reviews it from their account and approves or declines it.",
      },
      {
        q: "What happens before the customer approves?",
        a: "The rental does not start. The offer stays in \"awaiting customer review\", and the customer can read the full contract before any commitment.",
      },
      {
        q: "What is documented at receipt?",
        a: "Confirmation that the item was received, its condition at that moment (good, or with notes), and the time it was recorded. The same happens at return.",
      },
      {
        q: "What happens if there is a dispute?",
        a: "A documented case (damage or non-return) is opened with a description, evidence and a claim amount, and followed on a structured track linked to the contract. Lend organizes the documentation and the process; it is not a court or an arbitrator and does not guarantee any legal outcome.",
      },
      {
        q: "Does Lend verify identity with the government?",
        a: "No. The mobile verification code only confirms access to your Lend account. The national ID the business records in the contract is contractual data for that rental, which the customer reviews and accepts; it is not verified by Lend or any government system.",
      },
      {
        q: "Can rental businesses join Lend?",
        a: "Yes. A business submits a joining request with its business, representative and branch details, and Lend reviews the request before activating the account. You can register your interest from this page.",
      },
    ],
  },
  businessCta: {
    eyebrow: "For rental businesses",
    title: "Turn your rental operations into a clearer, better-organized experience",
    body: "Register your interest and we will get in touch when onboarding opens.",
    cta: "Register your business interest",
    placeholder: {
      title: "Interest registration opens soon",
      body: "We are preparing the business interest form. Nothing has been sent, and this page does not collect any data yet.",
      listTitle: "What you will need when registration opens",
      list: ["Business name and activity", "Commercial registration number", "Authorized business representative", "Branches that will use Lend"],
      note: "We will announce the opening on this page.",
      close: "Got it",
    },
  },
  footer: {
    description:
      "A Saudi platform that structures rentals between customers and businesses: a documented contract, a recorded handover, and a clear path when disputes arise.",
    privacy: "Privacy Policy",
    terms: "Terms",
    contact: "Contact",
    copyright: "© 2026 Lend. All rights reserved.",
    madeIn: "Kingdom of Saudi Arabia",
  },
  legal: {
    privacy: {
      title: "Privacy Policy",
      body: "We are finalizing the privacy policy. It will be published on this page before the platform launches. Until then, this website does not collect any personal data.",
      updated: "This page is a placeholder",
    },
    terms: {
      title: "Terms",
      body: "We are finalizing the terms and conditions. They will be published on this page before the platform launches.",
      updated: "This page is a placeholder",
    },
    back: "Back to home",
  },
  notFound: {
    title: "Page not found",
    body: "The link you followed is incorrect or no longer available.",
    back: "Back to home",
  },
  mock: {
    offerTitle: "Rental offer",
    offerNo: "#R-2481",
    awaitingReview: "Awaiting your review",
    merchant: "Business",
    customer: "Customer",
    item: "Item",
    rentalValue: "Rental price",
    originalValue: "Item's original value",
    duration: "Duration",
    start: "Start",
    returnDate: "Return",
    branch: "Branch",
    currency: "SAR",
    days: "3 days",
    reviewApprove: "Review & approve",
    decline: "Decline offer",
    activity: "Activity",
    actIssued: "Business issued the offer and contract",
    actSent: "Offer sent to you",
    actAwaiting: "Awaiting your approval",
    now: "Now",
    contractTitle: "Rental contract R-2481",
    contractBetween: "Between Durrat Al-Anaqa and Sara Alqahtani",
    contractSubject: "1. Subject of the contract",
    contractSubjectBody: "The first party rents the item described above to the second party for the agreed period.",
    contractTerm: "2. Rental period",
    contractTermBody: "Starts on 21/07/2026 and ends when the item is returned on 24/07/2026 in the condition received.",
    contractLiability: "3. Second party's responsibility",
    contractLiabilityBody: "The second party undertakes to look after the item and return it on the agreed date.",
    readNext: "I've read the contract — Next",
    prev: "Back",
    documented: "Documented",
    documentedOn: "Documented on",
    contractNote: "Your contract is documented. You can return to it any time from the rental details.",
    viewContract: "View contract",
    confirmReceipt: "Confirm receipt",
    receivedFromCustomer: "Item received from the customer",
    itemCondition: "Item condition",
    conditionGood: "Good",
    conditionNotes: "With notes",
    handoverTime: "Recorded at",
    closeRental: "Close rental — returned",
    statusActive: "Active",
    rentalDetails: "Rental details",
    stageOf: "Stage 3 of 4 · Rental started",
    readyToReturn: "Ready to return? Hand the item in at the branch and the contract closes once receipt is confirmed.",
    caseTitle: "Open a case — R-2395",
    caseBanner: "Opening a case pauses the normal return path and moves the contract to the handling track. Every step is documented on the contract.",
    caseType: "Case type",
    caseDamage: "Damage to the item",
    caseNoReturn: "Non-return",
    caseDesc: "Case description",
    caseDescBody: "Tear in the outer layer of the bag at receipt.",
    evidence: "Evidence",
    claim: "Claim amount",
    caseOpened: "Case opened by the business",
    caseEvidenceAdded: "Evidence and description added",
    caseUnderReview: "Case under review",
    caseStatus: "Under review",
    approvedTitle: "Approved. Your rental has started.",
    approvedBody: "Your contract is documented. Collect the item from the Olaya branch and return it before 24/07.",
    requestNo: "Request no.",
    dashboardTitle: "Store dashboard",
    dashboardStore: "Durrat Al-Anaqa",
    verifiedStore: "Active account",
    statActive: "Active rentals",
    statAwaiting: "Awaiting customer review",
    statReturns: "Returns this week",
    statCases: "Open case",
    needsAttention: "Needs your attention",
    issueNew: "Issue a new rental contract",
    tagCustomerReview: "Customer review",
    tagLate: "4 days late",
    tagReturnTomorrow: "Return tomorrow",
    sampleItem1: "Evening dress — model V24",
    sampleItem2: "Handbag — Noura Alshammari",
    sampleItem3: "Classic watch — Fahad Aldossari",
    sampleStore: "Durrat Al-Anaqa — Olaya branch",
    sampleBranch: "Olaya branch, Riyadh",
    sampleCustomer: "Sara Alqahtani",
    contractApproved: "Customer approved the contract",
    customerConfirmed: "Sara Alqahtani — confirmed Lend account",
    customerPhone: "Customer mobile",
  },
};
