import type { SiteContent } from "./types";

export const en: SiteContent = {
  meta: {
    title: "Lend | A clearer, documented rental experience",
    description:
      "Lend is a Saudi rental platform that brings structure to rentals between customers and rental businesses: a clear offer, a documented contract, recorded handover, an organized rental history, and a structured path when something goes wrong.",
    ogAlt: "Lend — Rent with confidence. Document your right.",
    siteName: "Lend",
    keywords: ["Lend", "rental", "rental contract", "Saudi Arabia", "documented rental", "rental businesses"],
  },
  brand: {
    name: "Lend",
    tagline1: "Rent with confidence.",
    tagline2: "Document your right.",
    taglineFull: "Rent with confidence. Document your right.",
  },
  nav: {
    home: "Home",
    how: "How Lend works",
    customers: "For customers",
    business: "For businesses",
    faq: "FAQ",
    switchLabel: "Change language",
    switchTo: "العربية",
    cta: "Register your business interest",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    skip: "Skip to content",
  },
  hero: {
    eyebrow: "A Saudi rental platform",
    supporting:
      "Lend gives every rental a clear structure: an offer you can read before you agree, a contract both sides can return to, a recorded handover, and one organized history of every rental — with a clear path if a dispute arises.",
    primaryCta: "Explore Lend",
    secondaryCta: "For business owners",
    points: ["A documented contract for every rental", "Item condition recorded at handover", "A structured path when disputes arise"],
    screenLabel: "The rental offer and contract screen in the Lend app",
  },
  why: {
    eyebrow: "01 — Why Lend",
    title: "Undocumented rentals cost both sides",
    intro:
      "Most rental problems don't start at the dispute. They start on day one: missing details, scattered paperwork, and two different memories of what was agreed.",
    beforeTitle: "What happens today",
    afterTitle: "How Lend structures it",
    pains: [
      { title: "Unclear rental details", body: "Duration, price and terms agreed verbally or across scattered messages." },
      { title: "Scattered documentation", body: "Photos on a phone, paper receipts, and chats nobody can find later." },
      { title: "Unknown condition at handover", body: "No one can show what state the item was in when it changed hands." },
      { title: "Weak transaction records", body: "No single record of every rental and where it stands." },
      { title: "Disputes without organized evidence", body: "When things go wrong, each side relies on its own account." },
    ],
    gains: [
      { title: "Clear rental details", body: "Item, price, duration and branch in one offer before anyone agrees." },
      { title: "A contractual record", body: "A rental contract that keeps the agreed terms, available to both sides at any time." },
      { title: "Documented handover and receipt", body: "The item's condition is recorded at pickup and at return." },
      { title: "An organized rental history", body: "Every rental in one place, with its current status." },
      { title: "A structured dispute journey", body: "A documented case with a description and evidence, instead of an open argument." },
    ],
  },
  how: {
    eyebrow: "02 — How Lend works",
    title: "One rental journey, four clear stages",
    intro:
      "Every rental on Lend moves through the same stages, and both sides can see exactly where it stands at any moment.",
    stagesTitle: "Stages of a rental",
    stages: ["Offer & contract issued", "Customer review", "Rental starts", "Return & contract closed"],
    customerTitle: "The customer journey",
    customerSub: "From receiving the offer to closing the rental",
    customer: [
      { title: "Receive the rental offer", body: "The business sends the offer to your Lend account." },
      { title: "Review the details and contract", body: "Item, price, duration and contract terms, before any commitment." },
      { title: "Approve in the app", body: "Your approval is recorded on the contract itself." },
      { title: "Document the receipt", body: "The item's condition is recorded when you collect it from the branch." },
      { title: "Manage your rental", body: "Status, return date and contract in one place." },
      { title: "Return and close", body: "The contract closes once the return is confirmed." },
    ],
    merchantTitle: "The business journey",
    merchantSub: "From confirming the customer to closing the contract",
    merchant: [
      { title: "Confirm the customer's account", body: "Using the mobile number registered on Lend." },
      { title: "Prepare the rental details", body: "Item description, original value, rental price and duration." },
      { title: "Record the contractual data", body: "Customer and item details exactly as they will appear in the contract." },
      { title: "Issue the offer and contract", body: "Sent to the customer to review and approve." },
      { title: "Follow the rental lifecycle", body: "From the start of the rental to the return date." },
      { title: "Manage returns and issues", body: "Confirm receipt, or open a documented damage or non-return case." },
    ],
  },
  customers: {
    eyebrow: "03 — For customers",
    title: "Know everything before you agree",
    intro: "Lend gives you the full picture before you commit, and keeps a record of what happens after.",
    benefits: [
      { icon: "eye", title: "See the rental details before approving", body: "Item, price, duration and branch are clear in the offer." },
      { icon: "document", title: "A clear contract and clear data", body: "Contract terms in plain language, available to you at any time." },
      { icon: "camera", title: "Condition recorded at receipt", body: "The item's condition is documented at pickup, so there is no argument later." },
      { icon: "history", title: "An organized record of your rentals", body: "Active, upcoming and completed, in one list." },
      { icon: "route", title: "A clear path if there is a dispute", body: "If a case is opened, you know what was documented and what is expected of you." },
    ],
  },
  business: {
    eyebrow: "04 — For rental businesses",
    title: "Operational infrastructure for your rental business",
    intro:
      "Lend is not a marketplace for listing products. It is the layer that structures every rental in your store, from issuing the offer to closing the contract.",
    items: [
      { icon: "route", title: "A standardized rental journey", body: "The same steps for every customer and every branch." },
      { icon: "document", title: "Organized contracts", body: "A contract for every rental, stored and linked to the customer and the item." },
      { icon: "phone", title: "Customer account confirmation", body: "Offers are issued to an account confirmed via the mobile number registered on Lend." },
      { icon: "camera", title: "Evidence and documentation", body: "Item condition at handover and return, plus evidence attached to cases." },
      { icon: "layers", title: "Centralized rental tracking", body: "One dashboard for every rental: active, awaiting review, and overdue." },
      { icon: "shield", title: "Structured dispute handling", body: "Damage or non-return cases with a description, evidence and claim amount, on a documented track." },
    ],
    cta: "Register your business interest",
  },
  product: {
    eyebrow: "05 — Product experience",
    title: "What the journey looks like inside Lend",
    intro: "Moments from the customer and business experience in the Lend app, in the product's own visual language.",
    labels: {
      offer: "Rental offer",
      contract: "Contract review",
      receipt: "Receipt evidence",
      status: "Rental status",
      dispute: "Case timeline",
    },
  },
  trust: {
    eyebrow: "06 — Trust & privacy",
    title: "Trust built on a clear record",
    intro:
      "Every rental on Lend has a confirmed account, a clear contract, and a connected record, leaving less room for ambiguity between business and customer.",
    items: [
      {
        icon: "lock",
        title: "Controlled account access",
        body: "Access to your account is tied to your registered mobile number and confirmed with a verification code sent to your phone. Your account and your rentals are yours alone.",
      },
      {
        icon: "document",
        title: "Clear contractual records",
        body: "Every rental has a contract that brings together both parties' details, the rental terms, and the agreed conditions, and it stays available to both sides throughout.",
      },
      {
        icon: "eye",
        title: "Customer review before confirmation",
        body: "No rental starts until the customer has reviewed the full offer and contract and approved them from their own account.",
      },
      {
        icon: "camera",
        title: "Documented receipt and return",
        body: "Item condition and the time of pickup and return are recorded on the contract itself, so both sides know exactly what was handed over, and when.",
      },
      {
        icon: "route",
        title: "Structured handling when parties differ",
        body: "If the two sides disagree, the case is documented with a description and evidence in a record linked to the contract, so the picture is clear and the handling steps can be followed from one place.",
      },
      {
        icon: "shield",
        title: "Care for sensitive data",
        body: "Contract data is shown only to the two parties of the rental, at the minimum each screen needs, and is never used for purposes outside your rental.",
      },
      {
        icon: "history",
        title: "An organized rental history",
        body: "All your rentals, with their status, contract, and documentation, in one record you can return to at any time.",
      },
    ],
    note: "Lend's role is to make every step of a rental clear and documented for both sides, from the first offer to the closed contract.",
  },
  faq: {
    eyebrow: "07 — FAQ",
    title: "Questions customers and businesses ask",
    intro: "Short answers that describe how Lend works today.",
    items: [
      {
        q: "What is Lend?",
        a: "Lend is a Saudi rental platform that structures rentals between customers and rental businesses: a clear offer, a documented contract, a recorded handover, an organized history of every rental, and a clear path when a dispute arises.",
      },
      {
        q: "Is Lend a rental marketplace?",
        a: "No. Lend does not list products and does not rent anything itself. The customer deals directly with the business; Lend structures and documents the rental.",
      },
      {
        q: "Who creates the rental contract?",
        a: "The business prepares the rental details and contractual data, then issues the offer and contract. The customer reviews it from their account and approves or declines it.",
      },
      {
        q: "What happens before the customer approves?",
        a: "The rental does not start. The offer stays in \"awaiting customer review\", and the customer can read the full contract before any commitment.",
      },
      {
        q: "What is documented at receipt?",
        a: "Confirmation that the item was received, its condition at that moment (good, or with notes), and the time it was recorded. The same happens at return.",
      },
      {
        q: "How does Lend help when the two parties disagree?",
        a: "Lend provides a structured path for documenting disagreements connected to a rental, so the contract details, claims, each party's notes, and the documentation records all appear in one clear record.\n\nThat makes it easier to understand the situation and follow the handling steps, instead of relying on scattered conversations or unorganized evidence.",
      },
      {
        q: "How does Lend document the parties to a rental?",
        a: "Lend links each rental to the customer's account and mobile number, and shows the customer the contract data entered by the business before approval, including the parties' details and the rental terms.\n\nThis gives both sides a clear digital record of the rental, with the contract, receipt, and notes connected in one place, reducing ambiguity and making each party's rights clearer.",
      },
      {
        q: "Can rental businesses join Lend?",
        a: "Yes. A business submits a joining request with its business, representative and branch details, and Lend reviews the request before activating the account. You can register your interest from this page.",
      },
    ],
  },
  businessCta: {
    eyebrow: "For rental businesses",
    title: "Turn your rental operations into a clearer, better-organized experience",
    body: "Register your interest and we will get in touch to show you how Lend works with your business.",
    cta: "Register your business interest",
    form: {
      title: "Register your business interest",
      intro: "Tell us about your business and the Lend partnerships team will get in touch.",
      labels: {
        business: "Business name",
        contact: "Contact person",
        mobile: "Mobile number",
        email: "Email address",
        type: "Business type",
        message: "Optional message",
      },
      placeholders: {
        business: "e.g. Durrat Al-Anaqa",
        contact: "e.g. Khalid Alotaibi",
        mobile: "05X XXX XXXX",
        email: "name@example.com",
        message: "Number of branches, rental volume, or anything else you would like us to know.",
      },
      typePlaceholder: "Select a business type",
      typeOptions: [
        { value: "dresses", label: "Dresses" },
        { value: "bags", label: "Bags" },
        { value: "watches", label: "Watches" },
        { value: "formalwear", label: "Formal wear" },
        { value: "equipment", label: "Equipment" },
        { value: "other", label: "Other" },
      ],
      optional: "Optional",
      requiredNote: "Fields marked * are required.",
      submit: "Send request",
      submitting: "Sending…",
      privacy: "We only use your details to get back to you about this request.",
      close: "Close",
      success: {
        title: "Your request has been sent successfully.",
        body: "We'll review your business details and contact you soon.",
        done: "Done",
      },
      errors: {
        required: "This field is required.",
        email: "Enter a valid email address.",
        mobile: "Enter a valid Saudi mobile number, e.g. 05X XXX XXXX.",
        type: "Select a business type.",
        tooLong: "This text is too long.",
        fixFields: "Please check the highlighted fields and try again.",
        unavailable: "Submission is temporarily unavailable. Please try again later.",
        rateLimited: "Too many attempts. Please try again in a few minutes.",
        generic: "Something went wrong while sending. Check your connection and try again.",
      },
    },
  },
  footer: {
    description:
      "A Saudi platform that structures rentals between customers and businesses: a documented contract, a recorded handover, and a clear path when disputes arise.",
    privacy: "Privacy Policy",
    terms: "Terms",
    contact: "Contact",
    copyright: "© 2026 Lend. All rights reserved.",
    madeIn: "Kingdom of Saudi Arabia",
  },
  legal: {
    back: "Back to home",
    contentsLabel: "Contents",
    effectiveLabel: "Last updated",
    contactLabel: "Privacy contact",
    privacy: {
      eyebrow: "Lend",
      title: "Privacy Policy",
      intro:
        "This policy explains what data Lend collects when you use the Lend app or the lend.sa website, how we use it, who we share it with, and the choices you have. It is written plainly so you know exactly what happens to your data.",
      effectiveDate: "14 September 2026",
      effectiveDateIso: "2026-09-14",
      contactEmail: "support@lend.sa",
      placeholder: false,
      sections: [
        {
          id: "who-we-are",
          heading: "Who we are and what this policy covers",
          paragraphs: [
            "Lend is a Saudi platform that structures rentals between customers and rental businesses: a rental offer, a contract the customer reviews and approves, documented handover and return, and a structured path when the parties disagree.",
            "This policy applies to the Lend app for customers and businesses and to the lend.sa website. Lend is not a party to the rental contract itself; it enables both parties to prepare, review, and document it.",
          ],
        },
        {
          id: "data-we-collect",
          heading: "Data we collect",
          paragraphs: ["We collect data you give us directly and data generated by your use of the service:"],
          bullets: [
            "Account data: full name, mobile number, email address, password (stored in hashed form, never readable by anyone), and city.",
            "Business data (for businesses): business name, trade name, commercial registration and unified numbers, business type, branch details (name, address, phone, opening hours), the business representative's details, and a copy of the commercial registration.",
            "Rental data: offer and contract details (item, value, duration, branch, rental terms and charges), the status and dates of each rental, and the parties' details as they appear in the contract. Contract data may include the customer's national ID number, entered by the business for that specific contract and reviewed by the customer before approval.",
            "Photos and documents: receipt photos the customer uploads when collecting an item, the photos and description a business uploads when opening a damage or non-return case, and notes either party adds along the case track.",
            "Verification codes: temporary codes sent to your mobile number or shown in the app to confirm access to your account or your presence when a contract is created.",
            "Notification data: your device's push notification identifier if you allow notifications, and your in-app notification history.",
            "Limited technical data: the app keeps a temporary, on-device log of error events for technical support, with personal data removed, which is cleared when you sign out.",
            "Business interest form on the website: business name, contact person, mobile number, email address, business type, and any message you choose to add.",
          ],
          after: [
            "We do not collect your device's location, and we do not use third-party analytics or advertising tools in the app or on the website.",
          ],
        },
        {
          id: "how-we-use",
          heading: "How we use data",
          bullets: [
            "To create your account and confirm access to it.",
            "To prepare rental offers and contracts and present them to the other party for review and approval.",
            "To document handover, return, and item condition, and to keep an organized record of your rentals.",
            "To handle damage or non-return cases on a documented track visible to both parties.",
            "To review business applications and activate business accounts.",
            "To send notifications about your rentals, such as a new offer or a case update.",
            "To provide technical support, fix errors, and protect the service from abuse.",
            "To contact businesses that register their interest through the website.",
          ],
          after: ["We do not sell your data and do not use it for third-party marketing."],
        },
        {
          id: "identity",
          heading: "Identity data in contracts",
          paragraphs: [
            "Access to your account is confirmed with a code sent to your registered mobile number or shown in the app. This confirmation relates to your Lend account.",
            "The national ID number shown in a rental contract is entered by the business as contractual data for that contract and is reviewed and approved by the customer during contract review. Lend keeps it as part of the contract record, and it is visible only to the two parties of that rental.",
          ],
        },
        {
          id: "sharing",
          heading: "Who we share data with",
          bullets: [
            "The other party to the rental: contract, handover, and case data is visible only to the business and the customer involved in that rental, and only as needed to complete it.",
            "Service providers working on our behalf: cloud hosting, database and file storage, SMS delivery of verification codes, push notification delivery through Apple and Google services, and email delivery for the website form. They process data under our instructions and only to operate the service.",
            "Authorities: where the law requires it, or to protect the rights of Lend or its users.",
          ],
          after: ["Push notifications never contain names, amounts, ID numbers, or verification codes; they carry a generic alert and an in-app link only."],
        },
        {
          id: "retention",
          heading: "How long we keep data",
          bullets: [
            "Account and rental data: for as long as your account exists.",
            "Verification codes: expire within minutes and are not used afterwards.",
            "Documents uploaded during a business registration that is never completed: deleted automatically within 24 hours.",
            "The temporary on-device technical log: cleared when you sign out.",
            "Business interest form: kept in the partnerships team's mailbox to follow up on your request.",
          ],
          after: [
            "When you request account deletion, the account is suspended immediately and a 30-day grace period begins, after which your data is permanently deleted. We may keep the minimum records required by law or needed to close an open case.",
          ],
        },
        {
          id: "security",
          heading: "How we protect data",
          paragraphs: [
            "Your data is encrypted in transit between your device and our servers and stored with a cloud hosting provider under access controls that prevent any user from viewing data that is not theirs. Passwords are never stored in readable form, and verification codes are generated on the server and never sent inside notifications.",
            "No method of transmission or storage is completely secure, so we review our controls continuously and ask you to protect your sign-in details and never share verification codes with anyone.",
          ],
        },
        {
          id: "your-rights",
          heading: "Your rights and choices",
          bullets: [
            "View and update your account details from the Profile page in the app.",
            "Return to your contracts and rental history at any time inside the app.",
            "Manage push notifications from your device settings.",
            "Delete your account from inside the app (Profile, then Delete account). Deletion cannot be completed while a rental is active, a case is being handled, or a financial obligation is unsettled.",
            "Request a copy of your data, ask for a correction, or ask about any processing by contacting us.",
          ],
        },
        {
          id: "children",
          heading: "Minors",
          paragraphs: [
            "Lend's services are intended for people who are legally able to enter into rental contracts, and we do not knowingly collect data from minors. If you become aware that a minor has created an account, contact us so we can address it.",
          ],
        },
        {
          id: "changes",
          heading: "Changes to this policy",
          paragraphs: [
            "We may update this policy when the service or legal requirements change. The updated version is published on this page with its last-updated date, and if a change is material we will let you know in the app.",
          ],
        },
        {
          id: "contact",
          heading: "Contact us",
          paragraphs: [
            "For any question or request about your privacy or your data, email us at the address below and we will get back to you as soon as possible.",
          ],
        },
      ],
    },
    terms: {
      eyebrow: "Lend",
      title: "Terms",
      intro: "We are finalizing the terms and conditions. They will be published on this page before the platform launches.",
      effectiveDate: "",
      effectiveDateIso: "",
      contactEmail: "",
      placeholder: true,
      sections: [],
    },
  },
  notFound: {
    title: "Page not found",
    body: "The link you followed is incorrect or no longer available.",
    back: "Back to home",
  },
  mock: {
    offerTitle: "Rental offer",
    offerNo: "#R-2481",
    awaitingReview: "Awaiting your review",
    merchant: "Business",
    customer: "Customer",
    item: "Item",
    rentalValue: "Rental price",
    originalValue: "Item's original value",
    duration: "Duration",
    start: "Start",
    returnDate: "Return",
    branch: "Branch",
    currency: "SAR",
    days: "3 days",
    reviewApprove: "Review & approve",
    decline: "Decline offer",
    activity: "Activity",
    actIssued: "Business issued the offer and contract",
    actSent: "Offer sent to you",
    actAwaiting: "Awaiting your approval",
    now: "Now",
    contractTitle: "Rental contract R-2481",
    contractBetween: "Between Durrat Al-Anaqa and Sara Alqahtani",
    contractSubject: "1. Subject of the contract",
    contractSubjectBody: "The first party rents the item described above to the second party for the agreed period.",
    contractTerm: "2. Rental period",
    contractTermBody: "Starts on 21/07/2026 and ends when the item is returned on 24/07/2026 in the condition received.",
    contractLiability: "3. Second party's responsibility",
    contractLiabilityBody: "The second party undertakes to look after the item and return it on the agreed date.",
    readNext: "I've read the contract — Next",
    prev: "Back",
    documented: "Documented",
    documentedOn: "Documented on",
    contractNote: "Your contract is documented. You can return to it any time from the rental details.",
    viewContract: "View contract",
    confirmReceipt: "Confirm receipt",
    receivedFromCustomer: "Item received from the customer",
    itemCondition: "Item condition",
    conditionGood: "Good",
    conditionNotes: "With notes",
    handoverTime: "Recorded at",
    closeRental: "Close rental — returned",
    statusActive: "Active",
    rentalDetails: "Rental details",
    stageOf: "Stage 3 of 4 · Rental started",
    readyToReturn: "Ready to return? Hand the item in at the branch and the contract closes once receipt is confirmed.",
    caseTitle: "Open a case — R-2395",
    caseBanner: "Opening a case pauses the normal return path and moves the contract to the handling track. Every step is documented on the contract.",
    caseType: "Case type",
    caseDamage: "Damage to the item",
    caseNoReturn: "Non-return",
    caseDesc: "Case description",
    caseDescBody: "Tear in the outer layer of the bag at receipt.",
    evidence: "Evidence",
    claim: "Claim amount",
    caseOpened: "Case opened by the business",
    caseEvidenceAdded: "Evidence and description added",
    caseUnderReview: "Case under review",
    caseStatus: "Under review",
    approvedTitle: "Approved. Your rental has started.",
    approvedBody: "Your contract is documented. Collect the item from the Olaya branch and return it before 24/07.",
    requestNo: "Request no.",
    dashboardTitle: "Store dashboard",
    dashboardStore: "Durrat Al-Anaqa",
    verifiedStore: "Active account",
    statActive: "Active rentals",
    statAwaiting: "Awaiting customer review",
    statReturns: "Returns this week",
    statCases: "Open case",
    needsAttention: "Needs your attention",
    issueNew: "Issue a new rental contract",
    tagCustomerReview: "Customer review",
    tagLate: "4 days late",
    tagReturnTomorrow: "Return tomorrow",
    sampleItem1: "Evening dress — model V24",
    sampleItem2: "Handbag — Noura Alshammari",
    sampleItem3: "Classic watch — Fahad Aldossari",
    sampleStore: "Durrat Al-Anaqa — Olaya branch",
    sampleBranch: "Olaya branch, Riyadh",
    sampleCustomer: "Sara Alqahtani",
    contractApproved: "Customer approved the contract",
    customerConfirmed: "Sara Alqahtani — confirmed Lend account",
    customerPhone: "Customer mobile",
  },
};
